language: ruby
bundler_args: --without development
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
before_install:
  - sudo apt-get install -qq augeas-tools augeas-lenses libaugeas-dev libaugeas-ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  matrix:
  - PUPPET_GEM_VERSION="~> 2.6.0"
  - PUPPET_GEM_VERSION="~> 2.7.0"
  - PUPPET_GEM_VERSION="~> 3.0.0"
  - PUPPET_GEM_VERSION="~> 3.1.0"
  - PUPPET_GEM_VERSION="~> 3.2.0"
  - PUPPET_GEM_VERSION="~> 3.3.1"
matrix:
  allow_failures:
    - env: PUPPET_GEM_VERSION="~> 2.6.0"
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.6.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.6.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"
notifications:
  email: false